### ISSUE TITLE
Fix a small bug in `partition_utils.py`

### ISSUE THREAD

**Issue by Chinese-Coding** [YukeWang96/PPoPP22_QGTC#2]
# Fix a small bug in `partition_utils.py`
When I set up all the environments and prepared to run, the following error occurred in the system.
```
(qgtc) zfq@ASUS:~/QGTC_PPoPP22$ python 0_7a_eval_QGTC_cluster_GCN.py
Traceback (most recent call last):
  File "main_qgtc.py", line 12, in <module>
    from sampler import ClusterIter
  File "/home/zfq/QGTC_PPoPP22/sampler.py", line 7, in <module>
    from partition_utils import *
  File "/home/zfq/QGTC_PPoPP22/partition_utils.py", line 7, in <module>
    from dgl.transform import metis_partition
ModuleNotFoundError: No module named 'dgl.transform'
...... (just repeat)
```

So I entered the `partition_utils.py` file, and PyCharm prompted me that the code had the following problems
![image](https://github.com/YukeWang96/QGTC_PPoPP22/assets/137599793/92f1a46c-52ae-482f-955f-5586d026da9f)
## At first  
At first I thought it was because the dgl library was not installed, so I re-executed the command:
```
conda install -c dglteam dgl-cuda11.0
pip install torch requests
```
But it tells me everything is installed:
```
(qgtc) zfq@ASUS:~/QGTC_PPoPP22$ conda install -c dglteam dgl-cuda11.0
Channels:
 - dglteam
 - defaults
 - conda-forge
 - pytorch
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.
```

## GPT
Later, I asked GPT, and GPT told me that it might be a problem with the dgl library version. Different versions provide different APIs.
![image](https://github.com/YukeWang96/QGTC_PPoPP22/assets/137599793/e7a044b4-78a9-4dfe-8f2d-7d8208fa3e18)
Through the above two commands, I knew that the version of my dgl library was 0.9.1post1. So I went online to find all relevant documents and document addresses [https://docs.dgl.ai/en/0.9.x/api/python/transforms.html](url).
It turns out that the API provided by this version is `transforms` instead of `transform`.

## FIX
**So I made the following modifications and finally it ran successfully:**
![image](https://github.com/YukeWang96/QGTC_PPoPP22/assets/137599793/c043ea96-17a8-4020-bee0-63ad044c98e3)

### write at the end
The above content (including this paragraph) was translated by Google Translate. It may not be smooth. Please forgive me.

**Comment by YukeWang96** [comment]
Hi, Thanks for your interest, have you ever tried the docker solution by using `docker pull happy233/qgtc:updated`? I guess the reason behind this would be the incompatible version of the DGL library/APIs since the DGL library is always being updated.

**Comment by Chinese-Coding** [comment]
thank you for your reply.
I have tried using docker, but I encountered problems when downloading the image.
For well-known reasons, accessing overseas websites from mainland China is difficult, and although there are technical means to solve these problems (I also used them), download speeds are still slow and unstable.
I tried to change the node where docker downloads the image to the image source, but I found that it still started from
I gave up this method after many failed attempts.
I will try it here if I have time in the future.

**Comment by Chinese-Coding** [comment]
I tried using docker and found that it is really simple, but I also encountered the following bugs:
![image](https://github.com/YukeWang96/QGTC_PPoPP22/assets/137599793/b426f1fd-42d6-410a-880a-c7fc843d4891)
Fortunately, I also found the corresponding solution:
[https://github.com/NVIDIA/nvidia-container-toolkit/issues/287#issuecomment-1903945104](url)
